### ISSUE TITLE
Please relicense as MIT

### ISSUE THREAD

**Issue by DanielShaulov** [khooz/nothing#2]
I want to use this in my commercial products, so it would be really nice if this was licensed under MIT or another permissive license

**Comment by khooz** [comment]
I'm sorry to hear that, but I believe nothing should be a copy-left licensed project, so it uses GPL 3.0 which lets anyone use it.

You can use it in your commercial products, provided that you disclose THIS same source code (which is nothing) with this same license for the said source code (which I re-iterate, there is none at all). Since anything is largely modified from nothing, any code you add to your commercial project can be subject to another licensing scheme and terms of your choice. So there is nothing you should be worrying about.

Thanks for choosing this project as the base of your products.
